language: node_js
node_js:
  - "stable"
cache:
  directories:
  - node_modules
script:
  - npm test -- --coverage # Include coverage when running tests
after_script: # Upload coverage reports 
  - COVERALLS_REPO_TOKEN=MRLYs5JzdECQqQFJQOqISkaqTC71XtuW5
# deploy:
#   provider: pages
#   skip_cleanup: true
#   local_dir: build
#   on:
#     branch: develop
